<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MoreQuestsFramework</AssemblyName>
    <RootNamespace>MoreQuestsFramework</RootNamespace>
    <Version>2.4.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net6.0</TargetFramework>
    <EnableHarmony>true</EnableHarmony>
    <ModFolderName>MoreQuestsFramework</ModFolderName>
    <EnableModZip>true</EnableModZip>
    <IgnoreModFilePaths>config.json</IgnoreModFilePaths>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="docs\**\*.cs" />
    <None Remove="docs\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GamePath)\smapi-internal\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
