using System.Collections.Generic;

namespace MoreQuests.Framework;

/// <summary>
/// Represents a quest generated by the mod.
/// </summary>
internal sealed class GeneratedQuest
{
    public string Id { get; set; } = "";
    public QuestCategory Category { get; set; }
    public DifficultyTier Tier { get; set; }
    public string QuestGiverNpc { get; set; } = "";

    // Objective
    public string ObjectiveItemId { get; set; } = "";
    public string ObjectiveItemName { get; set; } = "";
    public int ObjectiveQuantity { get; set; }
    public int MinQuality { get; set; }
    public string? TargetNpc { get; set; }
    public string? TargetMonster { get; set; }
    public string? TargetLocation { get; set; }

    // Deadline
    public int DeadlineDays { get; set; } = 2;

    // Rewards
    public int GoldReward { get; set; }
    public int FriendshipReward { get; set; }
    public string? FriendshipRewardNpc { get; set; }
    public string? ItemReward { get; set; }
    public string? RecipeReward { get; set; }

    // Consequences
    public List<QuestConsequence> Consequences { get; set; } = new();
    public bool HasNegativeConsequences => Consequences.Exists(c => c.FriendshipChange < 0);

    // Cooking-specific
    public List<RecipeIngredient>? RecipeIngredients { get; set; }
}

internal sealed class QuestConsequence
{
    public string NpcName { get; set; } = "";
    public int FriendshipChange { get; set; }
    public ConsequenceTier Tier { get; set; }
    public string DialogueKey { get; set; } = "";
}

internal enum ConsequenceTier
{
    Positive,
    Mild,
    Moderate,
    Significant
}
